const jssha = require('jssha');

const { SALT } = process.env;

function getHash(input) {
  // eslint-disable-next-line new-cap
  const shaObj = new jssha('SHA-512', 'TEXT', { encoding: 'UTF8' });
  const unhasedString = `${input}-${SALT}`;
  shaObj.update(unhasedString);

  return shaObj.getHash('HEX');
}

module.exports = {
  up: async (queryInterface) => {
    await queryInterface.bulkInsert('organisations', [
      {
        name: 'Rocket Industries',
        created_at: new Date(),
        updated_at: new Date(),
      },
    ]);
    await queryInterface.bulkInsert('users', [
      {
        username: 'admin',
        real_name: 'Neo Kai Yuan',
        password: getHash('testuser123'),
        organisation_id: 1,
        role: 'admin',
        wage: 10000.00,
        remaining_leaves: 0,
        remaining_shifts: 0,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        username: 'chee_kean',
        real_name: 'Chee Kean',
        password: getHash('testuser123'),
        organisation_id: 1,
        role: 'worker',
        wage: 1500.00,
        remaining_leaves: 0,
        remaining_shifts: 0,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        username: 'susan_chan',
        real_name: 'Susan Chan',
        password: getHash('testuser123'),
        organisation_id: 1,
        role: 'worker',
        wage: 1500.00,
        remaining_leaves: 0,
        remaining_shifts: 0,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        username: 'akira_wong',
        real_name: 'Akira Wong',
        password: getHash('testuser123'),
        organisation_id: 1,
        role: 'worker',
        wage: 1500.00,
        remaining_leaves: 0,
        remaining_shifts: 0,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        username: 'justin_wong',
        real_name: 'Justin Wong',
        password: getHash('testuser123'),
        organisation_id: 1,
        role: 'worker',
        wage: 1500.00,
        remaining_leaves: 0,
        remaining_shifts: 0,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        username: 'jia_en',
        real_name: 'Chiew Jia En',
        password: getHash('testuser123'),
        organisation_id: 1,
        role: 'worker',
        wage: 1500.00,
        remaining_leaves: 0,
        remaining_shifts: 0,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        username: 'shen_nan',
        real_name: 'Wong Shen Nan',
        password: getHash('testuser123'),
        organisation_id: 1,
        role: 'worker',
        wage: 1500.00,
        remaining_leaves: 0,
        remaining_shifts: 0,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        username: 'chuan_xin',
        real_name: 'Lee Chuan Xin',
        password: getHash('testuser123'),
        organisation_id: 1,
        role: 'worker',
        wage: 1500.00,
        remaining_leaves: 0,
        remaining_shifts: 0,
        created_at: new Date(),
        updated_at: new Date(),
      },
    ]);

    await queryInterface.bulkInsert('events', [
      // Chee Kean
      {
        user_id: 2,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-24'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 2,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-27'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 2,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-28'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 2,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-03'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 2,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-06'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 2,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-23'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      // Susan Chan
      {
        user_id: 3,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-01'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 3,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-06'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 3,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-13'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 3,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-02'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 3,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-07'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 3,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-15'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      // Akira Wong
      {
        user_id: 4,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-02'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 4,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-06'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 4,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-24'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 4,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-01'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 4,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-08'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 4,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-31'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      // Justin Wong
      {
        user_id: 5,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-31'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 5,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-30'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 5,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-29'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 5,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-28'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 5,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-27'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 5,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-24'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      // Chiew Jia En
      {
        user_id: 6,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-10'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 6,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-17'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 6,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-20'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 6,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-29'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 6,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-09'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 6,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-30'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      // Wong Shen Nan
      {
        user_id: 7,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-15'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 7,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-16'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 7,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-17'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 7,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-10'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 7,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-13'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 7,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-14'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      // Lee Chuan Xin
      {
        user_id: 8,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-23'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 8,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-24'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 8,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-27'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 8,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-28'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 8,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-29'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 8,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-30'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 8,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-31'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 8,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-16'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 8,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-17'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 8,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-20'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 8,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-21'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 8,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-22'),
        created_at: new Date(),
        updated_at: new Date(),
      },
    ]);

    await queryInterface.bulkInsert('schedules', [
      {
        is_selected: false,
        organisation_id: 1,
        start_month_date: new Date('2021-12-01'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        is_selected: false,
        organisation_id: 1,
        start_month_date: new Date('2021-12-01'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        is_selected: false,
        organisation_id: 1,
        start_month_date: new Date('2021-12-01'),
        created_at: new Date(),
        updated_at: new Date(),
      },
    ]);

    await queryInterface.bulkInsert('optimisations', [
      // Chee Kean
      {
        schedule_id: 1,
        user_id: 2,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-24'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 1,
        user_id: 2,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-27'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 1,
        user_id: 2,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-28'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 1,
        user_id: 2,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-06'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 1,
        user_id: 2,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-08'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 1,
        user_id: 2,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-23'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      // Susan Chan
      {
        schedule_id: 1,
        user_id: 3,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-01'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 1,
        user_id: 3,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-06'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 1,
        user_id: 3,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-13'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 1,
        user_id: 3,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-30'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 1,
        user_id: 3,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-07'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 1,
        user_id: 3,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-15'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      // Akira Wong
      {
        schedule_id: 1,
        user_id: 4,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-02'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 1,
        user_id: 4,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-06'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 1,
        user_id: 4,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-24'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 1,
        user_id: 4,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-28'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 1,
        user_id: 4,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-03'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 1,
        user_id: 4,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-31'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      // Justin Wong
      {
        schedule_id: 1,
        user_id: 5,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-31'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 1,
        user_id: 5,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-30'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 1,
        user_id: 5,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-29'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 1,
        user_id: 5,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-01'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 1,
        user_id: 5,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-27'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 1,
        user_id: 5,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-24'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      // Chiew Jia En
      {
        schedule_id: 1,
        user_id: 6,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-10'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 1,
        user_id: 6,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-17'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 1,
        user_id: 6,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-20'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 1,
        user_id: 6,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-29'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 1,
        user_id: 6,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-16'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 1,
        user_id: 6,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-02'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      // Wong Shen Nan
      {
        schedule_id: 1,
        user_id: 7,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-15'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 1,
        user_id: 7,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-16'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 1,
        user_id: 7,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-17'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 1,
        user_id: 7,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-10'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 1,
        user_id: 7,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-13'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 1,
        user_id: 7,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-21'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      // Lee Chuan Xin
      {
        schedule_id: 1,
        user_id: 8,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-23'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 1,
        user_id: 8,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-24'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 1,
        user_id: 8,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-27'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 1,
        user_id: 8,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-28'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 1,
        user_id: 8,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-29'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 1,
        user_id: 8,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-30'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 1,
        user_id: 8,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-31'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 1,
        user_id: 8,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-17'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 1,
        user_id: 8,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-09'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 1,
        user_id: 8,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-20'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 1,
        user_id: 8,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-14'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 1,
        user_id: 8,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-22'),
        created_at: new Date(),
        updated_at: new Date(),
      },

      // SCHEDULE ID 2
      // Chee Kean
      {
        schedule_id: 2,
        user_id: 2,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-24'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 2,
        user_id: 2,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-27'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 2,
        user_id: 2,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-28'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 2,
        user_id: 2,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-23'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 2,
        user_id: 2,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-29'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 2,
        user_id: 2,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-31'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      // Susan Chan
      {
        schedule_id: 2,
        user_id: 3,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-01'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 2,
        user_id: 3,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-06'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 2,
        user_id: 3,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-13'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 2,
        user_id: 3,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-24'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 2,
        user_id: 3,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-28'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 2,
        user_id: 3,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-30'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      // Akira Wong
      {
        schedule_id: 2,
        user_id: 4,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-02'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 2,
        user_id: 4,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-06'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 2,
        user_id: 4,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-24'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 2,
        user_id: 4,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-17'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 2,
        user_id: 4,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-22'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 2,
        user_id: 4,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-27'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      // Justin Wong
      {
        schedule_id: 2,
        user_id: 5,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-31'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 2,
        user_id: 5,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-30'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 2,
        user_id: 5,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-29'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 2,
        user_id: 5,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-14'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 2,
        user_id: 5,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-16'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 2,
        user_id: 5,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-20'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      // Chiew Jia En
      {
        schedule_id: 2,
        user_id: 6,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-10'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 2,
        user_id: 6,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-17'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 2,
        user_id: 6,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-20'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 2,
        user_id: 6,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-13'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 2,
        user_id: 6,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-15'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 2,
        user_id: 6,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-21'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      // Wong Shen Nan
      {
        schedule_id: 2,
        user_id: 7,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-15'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 2,
        user_id: 7,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-16'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 2,
        user_id: 7,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-17'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 2,
        user_id: 7,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-02'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 2,
        user_id: 7,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-07'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 2,
        user_id: 7,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-09'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      // Lee Chuan Xin
      {
        schedule_id: 2,
        user_id: 8,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-23'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 2,
        user_id: 8,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-24'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 2,
        user_id: 8,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-27'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 2,
        user_id: 8,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-28'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 2,
        user_id: 8,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-29'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 2,
        user_id: 8,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-30'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 2,
        user_id: 8,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-31'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 2,
        user_id: 8,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-01'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 2,
        user_id: 8,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-03'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 2,
        user_id: 8,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-06'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 2,
        user_id: 8,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-08'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 2,
        user_id: 8,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-10'),
        created_at: new Date(),
        updated_at: new Date(),
      },

      // OPTIMISATION ID 3
      // Chee Kean
      {
        schedule_id: 3,
        user_id: 2,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-24'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 3,
        user_id: 2,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-27'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 3,
        user_id: 2,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-28'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 3,
        user_id: 2,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-16'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 3,
        user_id: 2,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-29'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 3,
        user_id: 2,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-31'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      // Susan Chan
      {
        schedule_id: 3,
        user_id: 3,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-01'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 3,
        user_id: 3,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-06'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 3,
        user_id: 3,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-13'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 3,
        user_id: 3,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-24'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 3,
        user_id: 3,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-27'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 3,
        user_id: 3,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-30'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      // Akira Wong
      {
        schedule_id: 3,
        user_id: 4,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-02'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 3,
        user_id: 4,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-06'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 3,
        user_id: 4,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-24'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 3,
        user_id: 4,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-28'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 3,
        user_id: 4,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-21'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 3,
        user_id: 4,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-23'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      // Justin Wong
      {
        schedule_id: 3,
        user_id: 5,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-31'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 3,
        user_id: 5,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-30'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 3,
        user_id: 5,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-29'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 3,
        user_id: 5,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-08'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 3,
        user_id: 5,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-10'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 3,
        user_id: 5,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-14'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      // Chiew Jia En
      {
        schedule_id: 3,
        user_id: 6,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-10'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 3,
        user_id: 6,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-17'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 3,
        user_id: 6,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-20'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 3,
        user_id: 6,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-02'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 3,
        user_id: 6,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-07'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 3,
        user_id: 6,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-09'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      // Wong Shen Nan
      {
        schedule_id: 3,
        user_id: 7,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-15'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 3,
        user_id: 7,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-16'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 3,
        user_id: 7,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-17'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 3,
        user_id: 7,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-01'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 3,
        user_id: 7,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-03'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 3,
        user_id: 7,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-06'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      // Lee Chuan Xin
      {
        schedule_id: 3,
        user_id: 8,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-23'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 3,
        user_id: 8,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-24'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 3,
        user_id: 8,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-27'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 3,
        user_id: 8,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-28'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 3,
        user_id: 8,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-29'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 3,
        user_id: 8,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-30'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 3,
        user_id: 8,
        organisation_id: 1,
        type: 'leave',
        date_at: new Date('2021-12-31'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 3,
        user_id: 8,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-13'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 3,
        user_id: 8,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-15'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 3,
        user_id: 8,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-17'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 3,
        user_id: 8,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-20'),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        schedule_id: 3,
        user_id: 8,
        organisation_id: 1,
        type: 'shift',
        date_at: new Date('2021-12-22'),
        created_at: new Date(),
        updated_at: new Date(),
      },
    ]);
  },
  // to create default world json here
  down: async (queryInterface) => {
    await queryInterface.bulkDelete('optimisations', null, {});
    await queryInterface.bulkDelete('schedules', null, {});
    // drop events before users, because events have foreign keys in users and orgs
    await queryInterface.bulkDelete('events', null, {});
    // drop users before orgs, because users have foreign keys in orgs
    await queryInterface.bulkDelete('users', null, {});
    await queryInterface.bulkDelete('organisations', null, {});
  },
};
